#spring.data.rest.basePath=/api
config:
  session-length: 300

server:
  servlet:
    context-path: /starter/api
  port: 8080

eclipselink:
  weaving:false

spring:
  web:
    resources:
      add-mappings: false

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    database-platform: org.hibernate.dialect.H2Dialect
    db1:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.springframework.security:  trace

hibernate:
  enable_lazy_load_no_trans: true
